name: Build project

on:
  push:

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build desktop
      run: ./gradlew :desktop:build
    - name: Build android
      run: ./gradlew :android:build
    - name: Build server
      run: ./gradlew :server:build

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Build image
      run: docker build . --file Dockerfile --tag pserwylo/retrowars:latest
